site_name: IST 263, Spring 2019 - M005
theme: cinder
copyright: Copyright by Avinash Kadaji
google_analytics:
  - UA-105238264-1
  - auto
extra_css:
  - "css/ist263.css"
pages:
- Home: 'index.md'
- Weekly Schedule:
  - Week 1 : 'schedule/week01.md'
  - Week 2 : 'schedule/week02.md'
  - Week 3 : 'schedule/week03.md'
  - Week 4 : 'schedule/week04.md' 
  - Week 5 : 'schedule/week05.md'  
  - Week 6 : 'schedule/week06.md'   
  - Week 7 : 'schedule/week07.md'   
  - Week 8 : 'schedule/week08.md'     
  #- Week 9 : 'schedule/week09.md'   
  - Week 10 : 'schedule/week11.md'
  #- Week 11 : 'schedule/week11.md'   
  #- Week 14 : 'schedule/week14.md'       
- About: 
  - Syllabus: 'syllabus.md'
  - Getting your Computer Ready: 'computer-setup.md'
  - Submit Homework & Pull Feedback: 'submit-howto.md'
  - Individual Project: 'projects/individual.md'
- Question Bank: 'question-bank.md'


plugins:
  - markdownextradata

extra:
  github:
    assignment_url: https://classroom.github.com/a/ueGpuaz0